default:
    @just --list

# --- Quality ---------------------------------------------------------------

qc: rs-fmt rs-lint

rs-fmt:
    cargo fmt --all

rs-lint:
    cargo clippy --all-targets --all-features --fix --allow-dirty

test:
    cargo test --workspace

# --- Dev -------------------------------------------------------------------

dev:
    cargo run -p todo-tui

# --- Build -----------------------------------------------------------------

build:
    cargo build --release
    mkdir -p ~/.local/bin
    install -m 755 target/release/todo ~/.local/bin/todo
    just install-config

install-config:
    #!/usr/bin/env bash
    set -euo pipefail
    case "$(uname -s)" in
        Darwin) dir="$HOME/Library/Application Support/todo-tui" ;;
        *)      dir="${XDG_CONFIG_HOME:-$HOME/.config}/todo-tui" ;;
    esac
    mkdir -p "$dir"
    cfg="$dir/config.toml"
    umask 077
    {
        echo "# Generated by just install-config"
        [[ -n "${TODO_ROOT_DIR:-}" ]]      && echo "root_dir = \"$TODO_ROOT_DIR\""
        [[ -n "${TODO_CONTEXT:-}" ]]       && echo "context_slug = \"$TODO_CONTEXT\""
    } > "$cfg"
    echo "Wrote $cfg"
