set dotenv-load := true

default:
    @just --list

# --- Quality ---------------------------------------------------------------

qc: rs-qc py-qc

rs-fmt:
    cargo fmt --all

rs-lint:
    cargo clippy --all-targets --all-features --fix --allow-dirty

rs-qc: rs-fmt rs-lint

py-qc:
    uv run ruff format api automation
    uv run ruff check --fix api automation
    uv run ty check api/app automation/flows

test: test-rs test-py

test-rs:
    cargo test --workspace

test-py:
    uv run --directory api pytest -q

# --- Dev -------------------------------------------------------------------

dev-tui:
    cargo run -p todo-tui

dev-api:
    DATABASE_URL="${DATABASE_URL:-sqlite+aiosqlite:///./api/todo.db}" uv run --directory api uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# --- Build -----------------------------------------------------------------

build-tui:
    cargo build --release
    mkdir -p ~/.local/bin
    install -m 755 target/release/todo-tui ~/.local/bin/todo
    just install-tui-config

install-tui-config:
    #!/usr/bin/env bash
    set -euo pipefail
    case "$(uname -s)" in
        Darwin) dir="$HOME/Library/Application Support/todo-tui" ;;
        *)      dir="${XDG_CONFIG_HOME:-$HOME/.config}/todo-tui" ;;
    esac
    mkdir -p "$dir"
    cfg="$dir/config.toml"
    umask 077
    {
        echo "# Generated by just install-tui-config"
        [[ -n "${TODO_API_URL:-}" ]]        && echo "base_url = \"$TODO_API_URL\""
        [[ -n "${TODO_API_KEY:-}" ]]        && echo "api_key = \"$TODO_API_KEY\""
        [[ -n "${TODO_CONTEXT:-}" ]]        && echo "context_slug = \"$TODO_CONTEXT\""
        [[ -n "${TODO_KEYCLOAK_URL:-}" ]]   && echo "keycloak_url = \"$TODO_KEYCLOAK_URL\""
        [[ -n "${TODO_OIDC_REALM:-}" ]]     && echo "oidc_realm = \"$TODO_OIDC_REALM\""
        [[ -n "${TODO_OIDC_CLIENT_ID:-}" ]] && echo "oidc_client_id = \"$TODO_OIDC_CLIENT_ID\""
    } > "$cfg"
    echo "Wrote $cfg"

# --- Local stack (compose) -------------------------------------------------

_compose *args:
    cd deploy && docker compose --env-file ../.env {{args}}

stack-up:
    just _compose up -d postgres api

stack-down:
    just _compose down

stack-logs:
    just _compose logs -f

db-up:
    just _compose up -d postgres

automation-up:
    just _compose up -d automation

automation-down:
    just _compose rm -sf automation

automation-logs:
    just _compose logs -f automation

# --- Remote ops ------------------------------------------------------------
# Requires SERVER=user@host in .env (auto-loaded).
# Usage: just remote-deploy
#        just remote-stack-up
#        just remote-ping

remote-deploy:
    #!/usr/bin/env bash
    set -euo pipefail
    host="root@${SERVER##*@}"
    echo "Syncing to $host:/srv/todo ..."
    rsync -az --delete \
        --exclude='.git' \
        --exclude='target/' \
        --exclude='.venv' \
        --exclude='__pycache__' \
        --exclude='api/todo.db' \
        --exclude='.env' \
        . "$host":/srv/todo
    echo "Done."

remote-deploy-env:
    #!/usr/bin/env bash
    set -euo pipefail
    host="root@${SERVER##*@}"
    scp .env "$host":/srv/todo/.env
    echo "Deployed .env to $host"

remote-stack-up:
    #!/usr/bin/env bash
    set -euo pipefail
    host="root@${SERVER##*@}"
    ssh "$host" "cd /srv/todo/deploy && docker compose -f docker-compose.yml -f docker-compose.prod.yml --env-file /srv/todo/.env up -d --build postgres api caddy automation"

remote-stack-down:
    #!/usr/bin/env bash
    set -euo pipefail
    host="root@${SERVER##*@}"
    ssh "$host" "cd /srv/todo/deploy && docker compose -f docker-compose.yml -f docker-compose.prod.yml --env-file /srv/todo/.env down"

remote-ssh:
    ssh "root@${SERVER##*@}"

remote-ping:
    #!/usr/bin/env bash
    set -euo pipefail
    echo "Pinging $TODO_API_URL/health ..."
    curl -sf "$TODO_API_URL/health" | python3 -m json.tool
    echo ""
    echo "Listing contexts ..."
    curl -sf -H "X-API-Key: $TODO_API_KEY" "$TODO_API_URL/contexts" | python3 -m json.tool

remote-prefect-ui:
    #!/usr/bin/env bash
    set -euo pipefail
    host="root@${SERVER##*@}"
    echo "Prefect UI -> http://localhost:4200  (Ctrl-C to close tunnel)"
    open http://localhost:4200
    ssh -N -L 4200:localhost:4200 "$host"

remote-automation-run:
    #!/usr/bin/env bash
    set -euo pipefail
    host="root@${SERVER##*@}"
    ssh "$host" "docker exec -e PREFECT_API_URL=http://localhost:4200/api deploy-automation-1 prefect deployment run snapshot-email/snapshot-email"
